// <auto-generated />
using System;
using Backend.Shared.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Shared.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527181423_AddSamples")]
    partial class AddSamples
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Modules.Patients.Domain.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_cpf");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("Backend.Modules.Samples.Domain.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TubeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tube_type");

                    b.HasKey("Id")
                        .HasName("pk_samples");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_samples_service_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_samples_status");

                    b.ToTable("samples", (string)null);
                });

            modelBuilder.Entity("Backend.Modules.ServiceOrders.Domain.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("exam_code");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("exam_name");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TubeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tube_type");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_order_items_service_order_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Backend.Modules.ServiceOrders.Domain.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("called_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_service_orders");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_service_orders_patient_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_service_orders_status");

                    b.ToTable("service_orders", (string)null);
                });

            modelBuilder.Entity("Backend.Modules.Samples.Domain.Sample", b =>
                {
                    b.OwnsOne("Backend.Modules.Samples.Domain.RejectionReason", "RejectionReason", b1 =>
                        {
                            b1.Property<Guid>("SampleId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("rejection_reason");

                            b1.Property<string>("Notes")
                                .HasColumnType("text")
                                .HasColumnName("rejection_notes");

                            b1.HasKey("SampleId");

                            b1.ToTable("samples");

                            b1.WithOwner()
                                .HasForeignKey("SampleId")
                                .HasConstraintName("fk_samples_samples_id");
                        });

                    b.Navigation("RejectionReason");
                });

            modelBuilder.Entity("Backend.Modules.ServiceOrders.Domain.OrderItem", b =>
                {
                    b.HasOne("Backend.Modules.ServiceOrders.Domain.ServiceOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_service_orders_service_order_id");
                });

            modelBuilder.Entity("Backend.Modules.ServiceOrders.Domain.ServiceOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
